// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXyxpQ7aiGTU-JwXt6S-ysoGZbN4OxHM',
    appId: '1:431271578750:web:9d0af158c78fe6c3e0dc2f',
    messagingSenderId: '431271578750',
    projectId: 'appnotification-85128',
    authDomain: 'appnotification-85128.firebaseapp.com',
    storageBucket: 'appnotification-85128.appspot.com',
    measurementId: 'G-MKCRR7DH40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EEHcI50HRqwrZzK6N2u4oK91L-5c8xs',
    appId: '1:431271578750:android:f2e54d2f5e2bd26ee0dc2f',
    messagingSenderId: '431271578750',
    projectId: 'appnotification-85128',
    storageBucket: 'appnotification-85128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2m5yYq1onImiy3rsMfwn69wvGQ26k3cw',
    appId: '1:431271578750:ios:b5eb23ae2f3c03b5e0dc2f',
    messagingSenderId: '431271578750',
    projectId: 'appnotification-85128',
    storageBucket: 'appnotification-85128.appspot.com',
    iosBundleId: 'com.example.psnEmployeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2m5yYq1onImiy3rsMfwn69wvGQ26k3cw',
    appId: '1:431271578750:ios:b5eb23ae2f3c03b5e0dc2f',
    messagingSenderId: '431271578750',
    projectId: 'appnotification-85128',
    storageBucket: 'appnotification-85128.appspot.com',
    iosBundleId: 'com.example.psnEmployeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgXyxpQ7aiGTU-JwXt6S-ysoGZbN4OxHM',
    appId: '1:431271578750:web:bd914acd9e894e83e0dc2f',
    messagingSenderId: '431271578750',
    projectId: 'appnotification-85128',
    authDomain: 'appnotification-85128.firebaseapp.com',
    storageBucket: 'appnotification-85128.appspot.com',
    measurementId: 'G-V1DB18ZZBW',
  );
}
